sudo: required
services:
  - docker

  before_install:
    - docker build -t priyasubramanitvr/docker-react -f Dockerfile.dev .

    script:
      - docker run priyasubramanitvr/docker-react npm run test -- --coverage 