language: generic 
services:
  - docker

  before_install:
    - docker build -t 2072020/docker-react1 -f Dockerfile.dev .

    script:
      - docker run 2072020/docker-react1 npm run test -- --coverage 